{
  "uid" : "16bfd1964ec0a585",
  "name" : "test order db create backup",
  "fullName" : "tests_api.test_bd.TestBackup#test_order_db_create_backup",
  "historyId" : "bbc51bc9e59c2f7de52280f53d30e264",
  "time" : {
    "start" : 1755654713974,
    "stop" : 1755654714282,
    "duration" : 308
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: Incorrect status code: 400",
  "statusTrace" : "self = <tests_api.test_bd.TestBackup object at 0x7f0a4e440770>\nget_token_backup_2 = ('db72debf-81e0-455e-94ab-3c590ad84bd3', {'email': 'testbackup2@gmail.com', 'password': 'gwqldBUEoNGUiBrKFeVv'}, '066dc8d1-2d0a-753b-8000-ba69b49e1e8c')\n\n    @allure.title('test order db create backup')\n    def test_order_db_create_backup(self, get_token_backup_2):\n        token, body, uuid = get_token_backup_2\n        response = API.post_db_backup_create(token=token, db_uuid=uuid)\n>       Checking.check_status_code(response, 200)\n\ntests_api/test_bd.py:448: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresult = <Response [400]>, status_code = 200\n\n    @staticmethod\n    def check_status_code(result: requests.models.Response, status_code: int):\n        \"\"\"\n        Method check status code\n        :param result: Response\n        :param status_code:\n        \"\"\"\n        with allure.step(f'Assert status code: {status_code} == Response status code: {result.status_code}'):\n>           assert status_code == result.status_code, f'Incorrect status code: {result.status_code}'\nE           AssertionError: Incorrect status code: 400\n\ntests_api/utils/checking.py:16: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "get_token_backup_2",
    "time" : {
      "start" : 1755654713665,
      "stop" : 1755654713974,
      "duration" : 309
    },
    "status" : "passed",
    "steps" : [ {
      "name" : "Assert status code: 200 == Response status code: 200",
      "time" : {
        "start" : 1755654713974,
        "stop" : 1755654713974,
        "duration" : 0
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: Incorrect status code: 400",
    "statusTrace" : "self = <tests_api.test_bd.TestBackup object at 0x7f0a4e440770>\nget_token_backup_2 = ('db72debf-81e0-455e-94ab-3c590ad84bd3', {'email': 'testbackup2@gmail.com', 'password': 'gwqldBUEoNGUiBrKFeVv'}, '066dc8d1-2d0a-753b-8000-ba69b49e1e8c')\n\n    @allure.title('test order db create backup')\n    def test_order_db_create_backup(self, get_token_backup_2):\n        token, body, uuid = get_token_backup_2\n        response = API.post_db_backup_create(token=token, db_uuid=uuid)\n>       Checking.check_status_code(response, 200)\n\ntests_api/test_bd.py:448: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresult = <Response [400]>, status_code = 200\n\n    @staticmethod\n    def check_status_code(result: requests.models.Response, status_code: int):\n        \"\"\"\n        Method check status code\n        :param result: Response\n        :param status_code:\n        \"\"\"\n        with allure.step(f'Assert status code: {status_code} == Response status code: {result.status_code}'):\n>           assert status_code == result.status_code, f'Incorrect status code: {result.status_code}'\nE           AssertionError: Incorrect status code: 400\n\ntests_api/utils/checking.py:16: AssertionError",
    "steps" : [ {
      "name" : "Endpoint: /db_backup_create",
      "time" : {
        "start" : 1755654714281,
        "stop" : 1755654714281,
        "duration" : 0
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Request:",
      "time" : {
        "start" : 1755654714281,
        "stop" : 1755654714281,
        "duration" : 0
      },
      "status" : "passed",
      "steps" : [ {
        "name" : "Headers: {'Content-Type': 'application/json', 'Authorization': {'db72debf-81e0-455e-94ab-3c590ad84bd3'}}",
        "time" : {
          "start" : 1755654714281,
          "stop" : 1755654714281,
          "duration" : 0
        },
        "status" : "passed",
        "steps" : [ ],
        "attachments" : [ ],
        "parameters" : [ ],
        "stepsCount" : 0,
        "attachmentsCount" : 0,
        "shouldDisplayMessage" : false,
        "hasContent" : false
      } ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 1,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    }, {
      "name" : "Response:",
      "time" : {
        "start" : 1755654714281,
        "stop" : 1755654714281,
        "duration" : 0
      },
      "status" : "passed",
      "steps" : [ {
        "name" : "Status code: 400",
        "time" : {
          "start" : 1755654714281,
          "stop" : 1755654714281,
          "duration" : 0
        },
        "status" : "passed",
        "steps" : [ ],
        "attachments" : [ ],
        "parameters" : [ ],
        "stepsCount" : 0,
        "attachmentsCount" : 0,
        "shouldDisplayMessage" : false,
        "hasContent" : false
      }, {
        "name" : "JSON: {\n    \"content\": \"db either not exist, not in good shape, or does not belong to the user\"\n}\n",
        "time" : {
          "start" : 1755654714281,
          "stop" : 1755654714281,
          "duration" : 0
        },
        "status" : "passed",
        "steps" : [ ],
        "attachments" : [ ],
        "parameters" : [ ],
        "stepsCount" : 0,
        "attachmentsCount" : 0,
        "shouldDisplayMessage" : false,
        "hasContent" : false
      } ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 2,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    }, {
      "name" : "Assert status code: 200 == Response status code: 400",
      "time" : {
        "start" : 1755654714281,
        "stop" : 1755654714281,
        "duration" : 0
      },
      "status" : "failed",
      "statusMessage" : "AssertionError: Incorrect status code: 400\n",
      "statusTrace" : "  File \"/home/runner/work/Oblache/Oblache/tests_api/utils/checking.py\", line 16, in check_status_code\n    assert status_code == result.status_code, f'Incorrect status code: {result.status_code}'\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 7,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Test Backup"
  }, {
    "name" : "parentSuite",
    "value" : "tests_api"
  }, {
    "name" : "subSuite",
    "value" : "TestBackup"
  }, {
    "name" : "host",
    "value" : "pkrvmubgrv54qmi"
  }, {
    "name" : "thread",
    "value" : "2724-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests_api.test_bd"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 39,
        "broken" : 127,
        "skipped" : 0,
        "passed" : 96,
        "unknown" : 0,
        "total" : 262
      },
      "items" : [ {
        "uid" : "edc1efa524b4c6",
        "reportUrl" : "https://lambotik.github.io/Oblache/476//#testresult/edc1efa524b4c6",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 400",
        "time" : {
          "start" : 1755568433328,
          "stop" : 1755568433631,
          "duration" : 303
        }
      }, {
        "uid" : "44c5a8b03fbb75ce",
        "reportUrl" : "https://lambotik.github.io/Oblache/475//#testresult/44c5a8b03fbb75ce",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 400",
        "time" : {
          "start" : 1755482794104,
          "stop" : 1755482794473,
          "duration" : 369
        }
      }, {
        "uid" : "e545260a72ef65b2",
        "reportUrl" : "https://lambotik.github.io/Oblache/474//#testresult/e545260a72ef65b2",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7fec7667c8f0>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1755396431963,
          "stop" : 1755396462634,
          "duration" : 30671
        }
      }, {
        "uid" : "922c6e1dd0765ab6",
        "reportUrl" : "https://lambotik.github.io/Oblache/473//#testresult/922c6e1dd0765ab6",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7fd87121f410>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1755309370601,
          "stop" : 1755309401150,
          "duration" : 30549
        }
      }, {
        "uid" : "e185b8185c28853",
        "reportUrl" : "https://lambotik.github.io/Oblache/472//#testresult/e185b8185c28853",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 502",
        "time" : {
          "start" : 1755223212887,
          "stop" : 1755223212887,
          "duration" : 0
        }
      }, {
        "uid" : "a4b3e5511d7a6769",
        "reportUrl" : "https://lambotik.github.io/Oblache/471//#testresult/a4b3e5511d7a6769",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f6d09f92e40>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1755136872037,
          "stop" : 1755136902447,
          "duration" : 30410
        }
      }, {
        "uid" : "748ff24db1615dd8",
        "reportUrl" : "https://lambotik.github.io/Oblache/470//#testresult/748ff24db1615dd8",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7fae4d8d4680>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1755050408105,
          "stop" : 1755050438615,
          "duration" : 30510
        }
      }, {
        "uid" : "7add227251febfbc",
        "reportUrl" : "https://lambotik.github.io/Oblache/469//#testresult/7add227251febfbc",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7fdb9f830800>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1754963886983,
          "stop" : 1754963917392,
          "duration" : 30409
        }
      }, {
        "uid" : "c17b8b8ce2932321",
        "reportUrl" : "https://lambotik.github.io/Oblache/468//#testresult/c17b8b8ce2932321",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f95c332eba0>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1754878208069,
          "stop" : 1754878238655,
          "duration" : 30586
        }
      }, {
        "uid" : "9edb6156da7a2d9b",
        "reportUrl" : "https://lambotik.github.io/Oblache/467//#testresult/9edb6156da7a2d9b",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 502",
        "time" : {
          "start" : 1754791991480,
          "stop" : 1754791991480,
          "duration" : 0
        }
      }, {
        "uid" : "2083d2c7ad05e948",
        "reportUrl" : "https://lambotik.github.io/Oblache/466//#testresult/2083d2c7ad05e948",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7fc291be5ee0>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1754704746746,
          "stop" : 1754704777198,
          "duration" : 30452
        }
      }, {
        "uid" : "770535b5434d5f5f",
        "reportUrl" : "https://lambotik.github.io/Oblache/465//#testresult/770535b5434d5f5f",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 502",
        "time" : {
          "start" : 1754618950041,
          "stop" : 1754618950041,
          "duration" : 0
        }
      }, {
        "uid" : "2b252731d11f8e2a",
        "reportUrl" : "https://lambotik.github.io/Oblache/464//#testresult/2b252731d11f8e2a",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f7b37a82810>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1754532669558,
          "stop" : 1754532700137,
          "duration" : 30579
        }
      }, {
        "uid" : "ecf069bc025baf63",
        "reportUrl" : "https://lambotik.github.io/Oblache/463//#testresult/ecf069bc025baf63",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 502",
        "time" : {
          "start" : 1754446165573,
          "stop" : 1754446165573,
          "duration" : 0
        }
      }, {
        "uid" : "3646de2cf481cfc",
        "reportUrl" : "https://lambotik.github.io/Oblache/462//#testresult/3646de2cf481cfc",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7fbcf819de50>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1754359926994,
          "stop" : 1754359957386,
          "duration" : 30392
        }
      }, {
        "uid" : "d7298072d95e2fd8",
        "reportUrl" : "https://lambotik.github.io/Oblache/461//#testresult/d7298072d95e2fd8",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f6aeac130e0>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1754274250904,
          "stop" : 1754274281318,
          "duration" : 30414
        }
      }, {
        "uid" : "d3d3d89f64cbbd07",
        "reportUrl" : "https://lambotik.github.io/Oblache/460//#testresult/d3d3d89f64cbbd07",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f323c23a7b0>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1754187911657,
          "stop" : 1754187942294,
          "duration" : 30637
        }
      }, {
        "uid" : "7b50cf5918dca4cf",
        "reportUrl" : "https://lambotik.github.io/Oblache/459//#testresult/7b50cf5918dca4cf",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f4c509e0ce0>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1754100247094,
          "stop" : 1754100277509,
          "duration" : 30415
        }
      }, {
        "uid" : "21d87b6a9cc8906",
        "reportUrl" : "https://lambotik.github.io/Oblache/458//#testresult/21d87b6a9cc8906",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f3468556600>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1754015169903,
          "stop" : 1754015200326,
          "duration" : 30423
        }
      }, {
        "uid" : "eb8c083c5e8a1270",
        "reportUrl" : "https://lambotik.github.io/Oblache/457//#testresult/eb8c083c5e8a1270",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.prohttp', port=443): Max retries exceeded with url: /cis_db1.areso.pro/backups/db_cen6maxr.sql (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f8f1c3e2360>: Failed to resolve 'dbend.areso.prohttp' ([Errno -2] Name or service not known)\"))",
        "time" : {
          "start" : 1753927747733,
          "stop" : 1753927778227,
          "duration" : 30494
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "16bfd1964ec0a585.json",
  "parameterValues" : [ ]
}